### ISSUE TITLE
Semi-runtime permissions

### ISSUE THREAD

**Issue by Madis0** [NiklasGollenstede/re-style#20]
reStyle has a lot of permissions, and that could scare away new users. So why not use [runtime permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions)?

- **storage** - could ask on install because I assume reStyle doesn't have a fallback for styles on extension storage 
- **nativeMessaging** - request when user wants to set up NativeExt
- **notifications** - opt-in or [don't use at all](https://github.com/NiklasGollenstede/re-style/issues/18)
- **tabs**, **webNavigation**, **<all_urls>** - I don't quite get their difference, but if they achieve the same goal, they can be asked on install

**Comment by NiklasGollenstede** [comment]
I added a section explaining the permissions to the README / AMO description.

I don't think reStyle can ditch any of the permissions, though. Here is a bit more technical detail:

> - "Access your data for all websites": To apply styles to any website you choose.

This is `<all_urls>` and will never go away.

> - "Access browser tabs": Apply styles to existing tabs (when installed/enabled/started).
> - "Access browser activity during navigation": Apply styles to new tabs/pages.

`tabs` and `webNavigation`. They may become unnecessary once reStyle can use `contentScripts.register`, but that is blocked by at least https://bugzilla.mozilla.org/show_bug.cgi?id=1423323. I actually want to patch that (and possibly some related stuff), let's see how that goes.

> - "Exchange messages with programs other than Firefox": Use NativeExt if installed. Useless otherwise.

`nativeMessaging`. The setup is already complicated enough without an extra prompt here. And without an application that *want's* to be contacted by reStyle, this doesn't do anything.

> - "Display notifications to you": Success messages after user actions, error messages.  Status changes.

`notifications`. I don't think I will ever remove them completely. More in the ticket you opened for this.

> - "Access recently closed tabs": Under some rare conditions, reStyle needs to open temporary popups. This is used to remove them from the history after they are closed.

`sessions`. It's actually pretty stupid that this usecase requires a permission. maybe Mozilla will add an exception that allows to query for closed tabs/windows that only ever had views of the current extension loaded without the permission.

So if there are any changes to the permissions, they will happen because the need for them disappears. I don't see dynamic permissions as a viable alternative.
