### ISSUE TITLE
Disable auto-update

### ISSUE THREAD

**Issue by Madis0** [NiklasGollenstede/re-style#5]
Currently, when editing a style this disclaimer is shown:

> Please note that changes made here are not permanent and will be overwritten on the next update of this style. To customize a style permanently, create a local copy of it.

What if you just added a way for users to disable auto-update for specific styles? In my opinion having to manually create a local copy breaks the convenience of a one-click install, especially since there isn't a one-click way to create a local copy either.

**Comment by NiklasGollenstede** [comment]
At least currently there is no auto-update anyway, you have to click the update button for individual styles or the general one on the options page manually.

I don't think I want people to edit remote styles, that doesn't fit the concept of remote styles being remote. I only added the edit functionality to view the style contents and for some quick tests. I don't think it'll stick around without at least enabling a preference first.

You do make a valid point about the "one-click way to create a local copy". That would also play well with a "Add style for this site" option like Stylish has (or used to have?).

**Comment by Madis0** [comment]
> I don't think I want people to edit remote styles, that doesn't fit the concept of remote styles being remote. I only added the edit functionality to view the style contents and for some quick tests. I don't think it'll stick around without at least enabling a preference first.

IMO that is the benefit of the extension - to easily get styles from the web, but that shouldn't restrict them to the online version.

>You do make a valid point about the "one-click way to create a local copy". 

Perhaps two buttons:
* "Duplicate locally" when editing an online style
* "Create a new style" for easily making a local style

**Comment by NiklasGollenstede** [comment]
I want a clear distinction between styles created and maintained by the user and by [someone on the internet]. So styles excluded from the auto-update would need to go in a different category anyway. I never liked the way Stylish for Firefox handled this.
Since I don't want to add and maintain a decent CSS editor, I don't think there is any benefit of the current inline editor over the text editor you can use to edit local files.
I think a button "Create local copy" on the All-Styles-page that disables the remote style would be convenient enough.
A "Create style (for ...)" button in the panel could share most of its workflow and implementation. 
I don't know when I'll find the time to implement this, though.

**Comment by NiklasGollenstede** [comment]
The next release will contain this and automatic style updates. 
Not sure when I'll find the time to do that, though.
