### ISSUE TITLE
"NativeEXT unavailable" when trying to enable developer options or UI

### ISSUE THREAD

**Issue by ReaperLXIX** [NiklasGollenstede/re-style#8]
to be exact the error reads "unsupported 16-Bit application"

**Comment by NiklasGollenstede** [comment]
I guess you got it working?

**Comment by ReaperLXIX** [comment]
yes and no, I got past the 16bit issue and it seems now it just gives me an error saying it cannot connect to the native counterpart "NativeEXT unavailable" when trying to enable UI or developer

**Comment by NiklasGollenstede** [comment]
Did you get these me messages after the setup?:
![image](https://user-images.githubusercontent.com/10552031/38286998-e0692348-378d-11e8-853a-d6ac59e8f93f.png)
The "and X Firefox add-ons" must say at least 1.

**Comment by ReaperLXIX** [comment]
yes I did and it says 0 chrome and 1 firefox

**Comment by ReaperLXIX** [comment]
I'm running nightly is that a factor? I would think not

**Comment by NiklasGollenstede** [comment]
> I'm running nightly is that a factor?

That may actually be the reason. When I tried nightly recently, It didn't work either. I think I got a different error message, though. 
It was `The extension reStyle is not installed in <some_dir>. [...]`. If you get that, it would be somewhat interesting for me, what `<some_dir>` is in your case (you can remove your username if it appears in there).
This is caused by a variable being set to a different value than expected. I don't have a workaround though. The only solution I can currently think of requires a lot of restructuring. I'd expect to spend at least 20 hours on that. Time I currently don't have.
If you'd want to use reStyle now, you have to do it with the release or beta version. The developer version is based on beta, but may also handle the variable in question differently.

Also, if you just left this review on AMO: https://addons.mozilla.org/en-US/firefox/addon/re-style/reviews/1095703/
I'd ask you to reconsider. reStyle does work in general, and there is just no way for me to properly respond to such reviews. Nightly is not a channel which people are supposed to use productively.
As a site note, scrollbar styles on websites don't work with the `userChrome.css` (and thus don't work with reStyle). They would require agent sheets, which can't be used anymore.

**Comment by ReaperLXIX** [comment]
ah I figured as much, no worries appreciate the help

**Comment by ReaperLXIX** [comment]
I edited the review as best I could

**Comment by NiklasGollenstede** [comment]
Thanks. I'll reply here if the situation changes.

**Comment by ReaperLXIX** [comment]
sounds good thanks

**Comment by NiklasGollenstede** [comment]
reStyle v0.4.0 with NativeExt v0.3.1 uses a completely different architecture. This issue should be resolved.
